language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
    - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
after_script:
  - git push origin refs/notes/tests:refs/notes/tests
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
